language: android
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-18

android:
  components:
    - tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository

script: ./gradlew build
